import Gender from '../../models/lookups/gender'
import mongoose from 'mongoose'
import logging from '../../config/logging'
import Country from '../../models/lookups/country'
import Language from '../../models/lookups/language'

const MONGO_OPTIONS = {
	useUnifiedTopology: true,
	useNewUrlParser: true,
	socketTimeoutMS: 30000,
	keepAlive: true,
	poolSize: 50,
	autoIndex: false,
	retryWrites: false,
	useFindAndModify: false, useCreateIndex: true
}

const MONGO = {
	host: "mongodb+srv://Usama123:Usama123@cluster0.oeivl.mongodb.net/Cluster0?retryWrites=true&w=majority",
	username: "superuser",
	password: "supersecretpasswords",
	options: MONGO_OPTIONS,
	url: "mongodb+srv://Usama123:Usama123@cluster0.oeivl.mongodb.net/Cluster0?retryWrites=true&w=majority"
}

const gender = [
	{ name_en: "Male", name_ar: "ذكر" },
	{ name: "Female" },
	{ name: "Other" }
]

const countryList = [
	{ name: "Afghanistan" },
	{ name: "Albania" },
	{ name: "Algeria" },
	{ name: "American Samoa" },
	{ name: "Andorra" },
	{ name: "Angola" },
	{ name: "Anguilla" },
	{ name: "Antarctica" },
	{ name: "Antigua and Barbuda" },
	{ name: "Argentina" },
	{ name: "Armenia" },
	{ name: "Aruba" },
	{ name: "Australia" },
	{ name: "Austria" },
	{ name: "Azerbaijan" },
	{ name: "Bahamas" },
	{ name: "Bahrain" },
	{ name: "Bangladesh" },
	{ name: "Barbados" },
	{ name: "Belarus" },
	{ name: "Belgium" },
	{ name: "Belize" },
	{ name: "Benin" },
	{ name: "Bermuda" },
	{ name: "Bhutan" },
	{ name: "Bolivia (Plurinational State of)" },
	{ name: "Bonaire, Sint Eustatius and Saba" },
	{ name: "Bosnia and Herzegovina" },
	{ name: "Botswana" },
	{ name: "Bouvet Island" },
	{ name: "Brazil" },
	{ name: "British Indian Ocean Territory" },
	{ name: "Brunei Darussalam" },
	{ name: "Bulgaria" },
	{ name: "Burkina Faso" },
	{ name: "Burundi" },
	{ name: "Cabo Verde" },
	{ name: "Cambodia" },
	{ name: "Cameroon" },
	{ name: "Canada" },
	{ name: "Cayman Islands" },
	{ name: "Central African Republic" },
	{ name: "Chad" },
	{ name: "Chile" },
	{ name: "China" },
	{ name: "Christmas Island" },
	{ name: "Cocos (Keeling) Islands" },
	{ name: "Colombia" },
	{ name: "Comoros" },
	{ name: "Congo (the Democratic Republic of the)" },
	{ name: "Congo" },
	{ name: "Cook Islands" },
	{ name: "Costa Rica" },
	{ name: "Croatia" },
	{ name: "Cuba" },
	{ name: "Curaçao" },
	{ name: "Cyprus" },
	{ name: "Czechia" },
	{ name: "Côte d'Ivoire" },
	{ name: "Denmark" },
	{ name: "Djibouti" },
	{ name: "Dominica" },
	{ name: "Dominican Republic" },
	{ name: "Ecuador" },
	{ name: "Egypt" },
	{ name: "El Salvador" },
	{ name: "Equatorial Guinea" },
	{ name: "Eritrea" },
	{ name: "Estonia" },
	{ name: "Eswatini" },
	{ name: "Ethiopia" },
	{ name: "Falkland Islands [Malvinas]" },
	{ name: "Faroe Islands" },
	{ name: "Fiji" },
	{ name: "Finland" },
	{ name: "France" },
	{ name: "French Guiana" },
	{ name: "French Polynesia" },
	{ name: "French Southern Territories" },
	{ name: "Gabon" },
	{ name: "Gambia" },
	{ name: "Georgia" },
	{ name: "Germany" },
	{ name: "Ghana" },
	{ name: "Gibraltar" },
	{ name: "Greece" },
	{ name: "Greenland" },
	{ name: "Grenada" },
	{ name: "Guadeloupe" },
	{ name: "Guam" },
	{ name: "Guatemala" },
	{ name: "Guernsey" },
	{ name: "Guinea" },
	{ name: "Guinea-Bissau" },
	{ name: "Guyana" },
	{ name: "Haiti" },
	{ name: "Heard Island and McDonald Islands" },
	{ name: "Holy See" },
	{ name: "Honduras" },
	{ name: "Hong Kong" },
	{ name: "Hungary" },
	{ name: "Iceland" },
	{ name: "India" },
	{ name: "Indonesia" },
	{ name: "Iran (Islamic Republic of)" },
	{ name: "Iraq" },
	{ name: "Ireland" },
	{ name: "Isle of Man" },
	{ name: "Israel" },
	{ name: "Italy" },
	{ name: "Jamaica" },
	{ name: "Japan" },
	{ name: "Jersey" },
	{ name: "Jordan" },
	{ name: "Kazakhstan" },
	{ name: "Kenya" },
	{ name: "Kiribati" },
	{ name: "Korea (the Democratic People{name: 's Republic of)" },
	{ name: "Korea (the Republic of)" },
	{ name: "Kuwait" },
	{ name: "Kyrgyzstan" },
	{ name: "Lao People{name: 's Democratic Republic" },
	{ name: "Latvia" },
	{ name: "Lebanon" },
	{ name: "Lesotho" },
	{ name: "Liberia" },
	{ name: "Libya" },
	{ name: "Liechtenstein" },
	{ name: "Lithuania" },
	{ name: "Luxembourg" },
	{ name: "Macao" },
	{ name: "Madagascar" },
	{ name: "Malawi" },
	{ name: "Malaysia" },
	{ name: "Maldives" },
	{ name: "Mali" },
	{ name: "Malta" },
	{ name: "Marshall Islands" },
	{ name: "Martinique" },
	{ name: "Mauritania" },
	{ name: "Mauritius" },
	{ name: "Mayotte" },
	{ name: "Mexico" },
	{ name: "Micronesia (Federated States of)" },
	{ name: "Moldova (the Republic of)" },
	{ name: "Monaco" },
	{ name: "Mongolia" },
	{ name: "Montenegro" },
	{ name: "Montserrat" },
	{ name: "Morocco" },
	{ name: "Mozambique" },
	{ name: "Myanmar" },
	{ name: "Namibia" },
	{ name: "Nauru" },
	{ name: "Nepal" },
	{ name: "Netherlands" },
	{ name: "New Caledonia" },
	{ name: "New Zealand" },
	{ name: "Nicaragua" },
	{ name: "Niger" },
	{ name: "Nigeria" },
	{ name: "Niue" },
	{ name: "Norfolk Island" },
	{ name: "Northern Mariana Islands" },
	{ name: "Norway" },
	{ name: "Oman" },
	{ name: "Pakistan" },
	{ name: "Palau" },
	{ name: "Palestine, State of" },
	{ name: "Panama" },
	{ name: "Papua New Guinea" },
	{ name: "Paraguay" },
	{ name: "Peru" },
	{ name: "Philippines" },
	{ name: "Pitcairn" },
	{ name: "Poland" },
	{ name: "Portugal" },
	{ name: "Puerto Rico" },
	{ name: "Qatar" },
	{ name: "Republic of North Macedonia" },
	{ name: "Romania" },
	{ name: "Russian Federation" },
	{ name: "Rwanda" },
	{ name: "Réunion" },
	{ name: "Saint Barthélemy" },
	{ name: "Saint Helena, Ascension and Tristan da Cunha" },
	{ name: "Saint Kitts and Nevis" },
	{ name: "Saint Lucia" },
	{ name: "Saint Martin (French part)" },
	{ name: "Saint Pierre and Miquelon" },
	{ name: "Saint Vincent and the Grenadines" },
	{ name: "Samoa" },
	{ name: "San Marino" },
	{ name: "Sao Tome and Principe" },
	{ name: "Saudi Arabia" },
	{ name: "Senegal" },
	{ name: "Serbia" },
	{ name: "Seychelles" },
	{ name: "Sierra Leone" },
	{ name: "Singapore" },
	{ name: "Sint Maarten (Dutch part)" },
	{ name: "Slovakia" },
	{ name: "Slovenia" },
	{ name: "Solomon Islands" },
	{ name: "Somalia" },
	{ name: "South Africa" },
	{ name: "South Georgia and the South Sandwich Islands" },
	{ name: "South Sudan" },
	{ name: "Spain" },
	{ name: "Sri Lanka" },
	{ name: "Sudan" },
	{ name: "Suriname" },
	{ name: "Svalbard and Jan Mayen" },
	{ name: "Sweden" },
	{ name: "Switzerland" },
	{ name: "Syrian Arab Republic" },
	{ name: "Taiwan (Province of China)" },
	{ name: "Tajikistan" },
	{ name: "Tanzania, United Republic of" },
	{ name: "Thailand" },
	{ name: "Timor-Leste" },
	{ name: "Togo" },
	{ name: "Tokelau" },
	{ name: "Tonga" },
	{ name: "Trinidad and Tobago" },
	{ name: "Tunisia" },
	{ name: "Turkey" },
	{ name: "Turkmenistan" },
	{ name: "Turks and Caicos Islands" },
	{ name: "Tuvalu" },
	{ name: "Uganda" },
	{ name: "Ukraine" },
	{ name: "United Arab Emirates" },
	{ name: "United Kingdom of Great Britain and Northern Ireland" },
	{ name: "United States Minor Outlying Islands" },
	{ name: "United States of America" },
	{ name: "Uruguay" },
	{ name: "Uzbekistan" },
	{ name: "Vanuatu" },
	{ name: "Venezuela (Bolivarian Republic of)" },
	{ name: "Viet Nam" },
	{ name: "Virgin Islands (British)" },
	{ name: "Virgin Islands (U.S.)" },
	{ name: "Wallis and Futuna" },
	{ name: "Western Sahara" },
	{ name: "Yemen" },
	{ name: "Zambia" },
	{ name: "Zimbabwe" },
	{ name: "Åland Islands" }
]

const languagesList = [
	{ name: 'Abkhazian' },
	{ name: 'Afar' },
	{ name: 'Afrikaans' },
	{ name: 'Akan' },
	{ name: 'Albanian' },
	{ name: 'Amharic' },
	{ name: 'Arabic' },
	{ name: 'Aragonese' },
	{ name: 'Armenian' },
	{ name: 'Assamese' },
	{ name: 'Avaric' },
	{ name: 'Avestan' },
	{ name: 'Aymara' },
	{ name: 'Azerbaijani' },
	{ name: 'Bambara' },
	{ name: 'Bashkir' },
	{ name: 'Basque' },
	{ name: 'Belarusian' },
	{ name: 'Bengali' },
	{ name: 'Bihari languages' },
	{ name: 'Bislama' },
	{ name: 'Bosnian' },
	{ name: 'Breton' },
	{ name: 'Bulgarian' },
	{ name: 'Burmese' },
	{ name: 'Catalan, Valencian' },
	{ name: 'Central Khmer' },
	{ name: 'Chamorro' },
	{ name: 'Chechen' },
	{ name: 'Chichewa, Chewa, Nyanja' },
	{ name: 'Chinese' },
	{ name: 'Church Slavonic, Old Bulgarian, Old Church Slavonic' },
	{ name: 'Chuvash' },
	{ name: 'Cornish' },
	{ name: 'Corsican' },
	{ name: 'Cree' },
	{ name: 'Croatian' },
	{ name: 'Czech' },
	{ name: 'Danish' },
	{ name: 'Divehi, Dhivehi, Maldivian' },
	{ name: 'Dutch, Flemish' },
	{ name: 'Dzongkha' },
	{ name: 'English' },
	{ name: 'Esperanto' },
	{ name: 'Estonian' },
	{ name: 'Ewe' },
	{ name: 'Faroese' },
	{ name: 'Fijian' },
	{ name: 'Finnish' },
	{ name: 'French' },
	{ name: 'Fulah' },
	{ name: 'Gaelic, Scottish Gaelic' },
	{ name: 'Galician' },
	{ name: 'Ganda' },
	{ name: 'Georgian' },
	{ name: 'German' },
	{ name: 'Gikuyu, Kikuyu' },
	{ name: 'Greek (Modern)' },
	{ name: 'Greenlandic, Kalaallisut' },
	{ name: 'Guarani' },
	{ name: 'Gujarati' },
	{ name: 'Haitian, Haitian Creole' },
	{ name: 'Hausa' },
	{ name: 'Hebrew' },
	{ name: 'Herero' },
	{ name: 'Hindi' },
	{ name: 'Hiri Motu' },
	{ name: 'Hungarian' },
	{ name: 'Icelandic' },
	{ name: 'Ido' },
	{ name: 'Igbo' },
	{ name: 'Indonesian' },
	{ name: 'Interlingua (International Auxiliary Language Association)' },
	{ name: 'Interlingue' },
	{ name: 'Inuktitut' },
	{ name: 'Inupiaq' },
	{ name: 'Irish' },
	{ name: 'Italian' },
	{ name: 'Japanese' },
	{ name: 'Javanese' },
	{ name: 'Kannada' },
	{ name: 'Kanuri' },
	{ name: 'Kashmiri' },
	{ name: 'Kazakh' },
	{ name: 'Kinyarwanda' },
	{ name: 'Komi' },
	{ name: 'Kongo' },
	{ name: 'Korean' },
	{ name: 'Kwanyama, Kuanyama' },
	{ name: 'Kurdish' },
	{ name: 'Kyrgyz' },
	{ name: 'Lao' },
	{ name: 'Latin' },
	{ name: 'Latvian' },
	{ name: 'Letzeburgesch, Luxembourgish' },
	{ name: 'Limburgish, Limburgan, Limburger' },
	{ name: 'Lingala' },
	{ name: 'Lithuanian' },
	{ name: 'Luba-Katanga' },
	{ name: 'Macedonian' },
	{ name: 'Malagasy' },
	{ name: 'Malay' },
	{ name: 'Malayalam' },
	{ name: 'Maltese' },
	{ name: 'Manx' },
	{ name: 'Maori' },
	{ name: 'Marathi' },
	{ name: 'Marshallese' },
	{ name: 'Moldovan, Moldavian, Romanian' },
	{ name: 'Mongolian' },
	{ name: 'Nauru' },
	{ name: 'Navajo, Navaho' },
	{ name: 'Northern Ndebele' },
	{ name: 'Ndonga' },
	{ name: 'Nepali' },
	{ name: 'Northern Sami' },
	{ name: 'Norwegian' },
	{ name: 'Norwegian Bokmål' },
	{ name: 'Norwegian Nynorsk' },
	{ name: 'Nuosu, Sichuan Yi' },
	{ name: 'Occitan (post 1500)' },
	{ name: 'Ojibwa' },
	{ name: 'Oriya' },
	{ name: 'Oromo' },
	{ name: 'Ossetian, Ossetic' },
	{ name: 'Pali' },
	{ name: 'Panjabi, Punjabi' },
	{ name: 'Pashto, Pushto' },
	{ name: 'Persian' },
	{ name: 'Polish' },
	{ name: 'Portuguese' },
	{ name: 'Quechua' },
	{ name: 'Romansh' },
	{ name: 'Rundi' },
	{ name: 'Russian' },
	{ name: 'Samoan' },
	{ name: 'Sango' },
	{ name: 'Sanskrit' },
	{ name: 'Sardinian' },
	{ name: 'Serbian' },
	{ name: 'Shona' },
	{ name: 'Sindhi' },
	{ name: 'Sinhala, Sinhalese' },
	{ name: 'Slovak' },
	{ name: 'Slovenian' },
	{ name: 'Somali' },
	{ name: 'Sotho, Southern' },
	{ name: 'South Ndebele' },
	{ name: 'Spanish, Castilian' },
	{ name: 'Sundanese' },
	{ name: 'Swahili' },
	{ name: 'Swati' },
	{ name: 'Swedish' },
	{ name: 'Tagalog' },
	{ name: 'Tahitian' },
	{ name: 'Tajik' },
	{ name: 'Tamil' },
	{ name: 'Tatar' },
	{ name: 'Telugu' },
	{ name: 'Thai' },
	{ name: 'Tibetan' },
	{ name: 'Tigrinya' },
	{ name: 'Tonga (Tonga Islands)' },
	{ name: 'Tsonga' },
	{ name: 'Tswana' },
	{ name: 'Turkish' },
	{ name: 'Turkmen' },
	{ name: 'Twi' },
	{ name: 'Uighur, Uyghur' },
	{ name: 'Ukrainian' },
	{ name: 'Urdu' },
	{ name: 'Uzbek' },
	{ name: 'Venda' },
	{ name: 'Vietnamese' },
	{ name: 'Volap_k' },
	{ name: 'Walloon' },
	{ name: 'Welsh' },
	{ name: 'Western Frisian' },
	{ name: 'Wolof' },
	{ name: 'Xhosa' },
	{ name: 'Yiddish' },
	{ name: 'Yoruba' },
	{ name: 'Zhuang, Chuang' },
	{ name: 'Zulu' }
]

const insertLookups = async () => {

	await mongoose.connect(MONGO.url, MONGO.options)

	console.log("Clearing the lookups first...")

	await Gender.deleteMany({})
	await Country.deleteMany({})
	await Language.deleteMany({})

	console.log("Inserting lookups")

	const options = { ordered: true }

	await Gender.insertMany(gender, options)
	//@ts-ignore
	console.log(`Genders were inserted`)

	await Country.insertMany(countryList, options)
	//@ts-ignore
	console.log("Countries were inserted")

	await Language.insertMany(languagesList, options)
	//@ts-ignore
	console.log("Languages were inserted")

	process.exit()

}

insertLookups()

// How to insert Lookups 
		// In the terminal, go to this directory first and then run following command
				// npx ts-node index.ts